source/objects/Error_Event_Log__c/Error_Event_Log__c.object-meta.xml
<CustomObject>
    <label>Error Event Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Error Event Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Error_Event_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

source/classes/ErrorEventLogTriggerHelper.cls
public with sharing class ErrorEventLogTriggerHelper {
    
    public static void getFix(Map<Id, Error_Event_Log__c> errorLogList) {
        Map<Id, Error_Event_Log__c> errorEventLogMap = new Map<Id, Error_Event_Log__c>();
        for(Error_Event_Log__c errorLog : errorLogList.values()){
            if(errorLog.Object__c != 'Error_Event_Log__c' && errorLog.Type__c == 'Error'){
                errorEventLogMap.put(errorLog.Id, errorLog);
            }
        }
        if(!errorEventLogMap.isEmpty()){
            ErrorEventLogBatch errorBatch = new ErrorEventLogBatch(errorEventLogMap);
            Database.executeBatch(errorBatch, 200);
        }
    }
    
}